alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
- rule: DEPLOYMENT_LIVE
- rule: DOMAIN_LIVE
databases:
- cluster_name: web-scheduler-prod
  engine: MYSQL
  name: web-scheduler-prod
  production: true
  version: "8"
- cluster_name: web-scheduler-redis
  engine: REDIS
  name: web-scheduler-redis
  production: true
  version: "6"
- cluster_name: web-scheduler-prod-nyc3-ro
  db_name: orleans
  db_user: orleans
  engine: MYSQL
  name: web-scheduler-prod-nyc3-ro
  production: true
  version: "8"
domains:
- domain: scheduler.nullreference.io
  type: PRIMARY
features:
- enable-kata-build
jobs:
- alerts:
  - operator: GREATER_THAN
    rule: CPU_UTILIZATION
    value: 80
    window: FIVE_MINUTES
  - operator: GREATER_THAN
    rule: MEM_UTILIZATION
    value: 80
    window: FIVE_MINUTES
  - operator: GREATER_THAN
    rule: RESTART_COUNT
    value: 1
    window: FIVE_MINUTES
  envs:
  - key: ASPNETCORE_ENVIRONMENT
    scope: RUN_AND_BUILD_TIME
    value: Production
  - key: Kestrel__Endpoints__Http__Url
    scope: RUN_TIME
    value: http://*:80
  - key: ConnectionStrings__Default
    scope: RUN_TIME
    value: Server=${web-scheduler-prod.HOSTNAME};Port=${web-scheduler-prod.PORT};Database=orleans;UserId=${web-scheduler-prod.USERNAME};Password=${web-scheduler-prod.PASSWORD};SslMode=Required;
  image:
    registry_type: DOCR
    repository: webscheduler-datamigrations
    tag: 0.1.38
  instance_count: 1
  instance_size_slug: professional-xs
  kind: PRE_DEPLOY
  name: web-scheduler-datamigrator-job
  run_command: /app/efbundle
name: web-scheduler
region: nyc
services:
- alerts:
  - operator: GREATER_THAN
    rule: CPU_UTILIZATION
    value: 80
    window: FIVE_MINUTES
  - operator: GREATER_THAN
    rule: MEM_UTILIZATION
    value: 80
    window: FIVE_MINUTES
  - operator: GREATER_THAN
    rule: RESTART_COUNT
    value: 1
    window: FIVE_MINUTES
  envs:
  - key: ASPNETCORE_ENVIRONMENT
    scope: RUN_AND_BUILD_TIME
    value: Production
  - key: Kestrel__Endpoints__Http__Url
    scope: RUN_TIME
    value: http://*:80
  - key: Storage__Invariant
    scope: RUN_AND_BUILD_TIME
    value: MySql.Data.MySqlClient
  - key: Storage__ConnectionString
    scope: RUN_TIME
    value: Server=${web-scheduler-prod.HOSTNAME};Port=${web-scheduler-prod.PORT};Database=orleans;UserId=${web-scheduler-prod.USERNAME};Password=${web-scheduler-prod.PASSWORD};SslMode=Required;
  - key: Serilog__MinimumLevel__Default
    scope: RUN_TIME
    value: Information
  health_check:
    http_path: /status/self
    port: 80
  http_port: 8080
  image:
    registry_type: DOCR
    repository: webscheduler-server
    tag: 0.1.38
  instance_count: 5
  instance_size_slug: professional-xl
  internal_ports:
  - 11111
  - 30000
  - 80
  name: web-scheduler-server
  routes:
  - path: /OrleansDashboard
    preserve_path_prefix: true
- alerts:
  - operator: GREATER_THAN
    rule: CPU_UTILIZATION
    value: 80
    window: FIVE_MINUTES
  - operator: GREATER_THAN
    rule: MEM_UTILIZATION
    value: 80
    window: FIVE_MINUTES
  - operator: GREATER_THAN
    rule: RESTART_COUNT
    value: 1
    window: FIVE_MINUTES
  envs:
  - key: Redis__ConnectionString
    scope: RUN_TIME
    value: ${web-scheduler-redis.HOSTNAME}:${web-scheduler-redis.PORT},user=${web-scheduler-redis.USERNAME},password=${web-scheduler-redis.PASSWORD},Ssl=true
  - key: Kestrel__Endpoints__Http__Url
    scope: RUN_TIME
    value: http://*:80
  - key: ForwardedHeaders__AllowedHosts
    scope: RUN_TIME
    value: ${APP_DOMAIN}
  - key: ASPNETCORE_ENVIRONMENT
    scope: RUN_AND_BUILD_TIME
    value: Production
  - key: Storage__Invariant
    scope: RUN_AND_BUILD_TIME
    value: MySql.Data.MySqlClient
  - key: Storage__ConnectionString
    scope: RUN_TIME
    value: Server=${web-scheduler-prod.HOSTNAME};Port=${web-scheduler-prod.PORT};Database=orleans;UserId=${web-scheduler-prod.USERNAME};Password=${web-scheduler-prod.PASSWORD};SslMode=Required;
  - key: Serilog__MinimumLevel__Default
    scope: RUN_TIME
    value: Information
  - key: ConnectionStrings__DataProtectionConnectionString
    scope: RUN_TIME
    value: Server=${web-scheduler-prod.HOSTNAME};Port=${web-scheduler-prod.PORT};Database=DataProtection;UserId=${web-scheduler-prod.USERNAME};Password=${web-scheduler-prod.PASSWORD};SslMode=Required;
  health_check:
    http_path: /status
    initial_delay_seconds: 120
  http_port: 80
  image:
    registry_type: DOCR
    repository: web-scheduler-api
    tag: 0.1.44
  instance_count: 3
  instance_size_slug: professional-xs
  name: web-scheduler-api
  routes:
  - path: /api
static_sites:
- catchall_document: index.html
  environment_slug: html
  github:
    branch: release
    deploy_on_push: true
    repo: web-scheduler/web-scheduler-frontend
  name: web-scheduler-frontend
  routes:
  - path: /
    preserve_path_prefix: true
